"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 20000

[character]
success_symbol = "[▷](bold green)"
error_symbol = "[✖](bold red)"

[aws]
disabled = true

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_state]
format = '($state( $progress_current of $progress_total)) '

[git_status]
staged = '[++\($count\)](green)'
ahead = "⇡${count}(red)"
diverged = "⇕⇡${ahead_count}⇣${behind_count}(bold red)"
behind = "⇣${count}(red)"
modified = "~${count}(yellow)"
