"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[➜](bold green)"

[aws]
disabled = true

[status]
disabled = false
format = '[$symbol$signal_name]($style) '

[git_status]
staged = '[++\($count\)](green)'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
